include-file = scripts/colors_vscode_dark

[bar/herbstluft]
background = ${colors_vscode_dark.bg_dark_translucent}
font-0 = "DejaVuSansM Nerd Font:pixelsize=10;3"
font-1 = "DejaVuSansM Nerd Font:pixelsize=6;3"
font-2 = "DejaVuSansM Nerd Font:pixelsize=12;3"
;font-2 = "Font Awesome 5 Free,Font Awesome 6 Free:style=Solid:pixelsize=12;2"
height = 25
width = 100%:-10
offset-x = 5
offset-y = 5
line-size = 3
modules-center = sptr power-off power-reboot power-lock power-logout sptr vol sptr cpul cpu dsp meml mem dsp netl nets dsp kbl kb sp sptr ewmh sptr date sptr upl ups sptr
monitor = ${env:MONITOR}
enable-ipc = true

[module/sp]
type = custom/text
format = |
format-background = ${colors_vscode_dark.bg_light}
format-foreground = ${colors_vscode_dark.fg_transparent}
format-padding = 0

[module/dsp]
type = custom/text
format = |
format-background = ${colors_vscode_dark.bg_light}
format-foreground = ${colors_vscode_dark.fg_transparent}
format-padding = 1

[module/sptr]
type = custom/text
format = |
format-background = ${colors_vscode_dark.bg_transparent}
format-foreground = ${colors_vscode_dark.fg_transparent}
format-padding = 0
format-font = 2

[module/sp_bgd]
type = custom/text
format = |
format-background = ${colors_vscode_dark.bg_dark}
format-foreground = ${colors_vscode_dark.fg_transparent}
format-padding = 0

[module/power-off]
type = custom/text
click-left = /sbin/poweroff
;fa-power-off
format = 
format-background = ${colors_vscode_dark.bg_red}
format-font = 3
format-foreground = ${colors_vscode_dark.fg_white}
format-padding = 2
;format-underline = ${colors_vscode_dark.line_red}

[module/power-reboot]
type = custom/text
click-left = /sbin/reboot
;fa-redo-alt
format = 
format-background = ${colors_vscode_dark.bg_yellow}
format-font = 3
format-foreground = ${colors_vscode_dark.fg_white}
format-padding = 2

[module/power-lock]
type = custom/text
click-left = physlock -dsm
;fa-lock
format = 
format-background = ${colors_vscode_dark.bg_green}
format-font = 3
format-foreground = ${colors_vscode_dark.fg_white}
format-padding = 2

[module/power-logout]
type = custom/text
click-left = herbstclient quit
;fa-right-from-bracket
format = 
format-background = ${colors_vscode_dark.bg_dark}
format-font = 3
format-foreground = ${colors_vscode_dark.fg_white}
format-padding = 2

[module/vol]
type = internal/pulseaudio
click-middle = easyeffects
click-right = pavucontrol
format-muted = <label-muted>
format-muted-background = ${colors_vscode_dark.bg_dark}
format-muted-padding = 2
format-volume = <label-volume>
format-volume-background = ${colors_vscode_dark.bg_dark}
format-volume-padding = 2
;fa-volume-mute, fa-volume-up
label-muted =  mute
label-volume =  %percentage:3%%
use-ui-max = false

;[module/vol]
;type = custom/script
;exec = ~/.config/herbstluftwm/polybar/scripts/pipewire.sh
;interval = 5
;click-right = pavucontrol
;click-left = ~/.config/herbstluftwm/polybar/scripts/pipewire.sh mute &
;format-background = ${colors_vscode_dark.bg_dark}
;format-padding = 2

[module/cpul]
type = custom/text
click-left = urxvt -name wrapper -e btm -C ~/.config/bottom/bottom-cpu.toml
click-right = urxvt -name wrapper -e btm -C ~/.config/bottom/bottom-processes.toml
;fa-microchip
format = 
format-background = ${colors_vscode_dark.bg_light}
format-foreground = ${colors_vscode_dark.fg_label}
format-padding = 1

[module/cpu]
type = internal/cpu
format = <label>
interval = 1
label = %percentage:2%%
label-background = ${colors_vscode_dark.bg_light}
label-foreground = ${colors_vscode_dark.fg_white}
label-minlen = 3
label-padding = 0

[module/meml]
type = custom/text
click-left = urxvt -name wrapper -e btm -C ~/.config/bottom/bottom-memory.toml
click-right = urxvt -name wrapper -e btm -C ~/.config/bottom/bottom-processes.toml
;fa-memory
format = 
format-background = ${colors_vscode_dark.bg_light}
format-foreground = ${colors_vscode_dark.fg_label}
format-padding = 1

[module/mem]
type = internal/memory
format = <label>
label = %gb_used:9% (%gb_total%)
label-background = ${colors_vscode_dark.bg_light}
label-foreground = ${colors_vscode_dark.fg_white}
label-minlen = 21
label-padding = 0

[module/netl]
type = custom/text
click-left = urxvt -name wrapper -e btm -C ~/.config/bottom/bottom-network.toml
click-middle = expressvpn-client
click-right = urxvt -name wrapper -e nmtui
;fa-network-wired
format = 
format-background = ${colors_vscode_dark.bg_light}
format-foreground = ${colors_vscode_dark.fg_label}
format-padding = 1

[module/nets]
type = custom/script
exec = ~/.config/herbstluftwm/polybar/scripts/network-interfaces.sh
click-left = urxvt -name wrapper -e btm -C ~/.config/bottom/bottom-network.toml
click-middle = expressvpn-client
click-right = urxvt -name wrapper -e nmtui
format-background = ${colors_vscode_dark.bg_light}
format-padding = 1

[module/kbl]
type = custom/text
;fa-keyboard
format = 
format-background = ${colors_vscode_dark.bg_light}
format-foreground = ${colors_vscode_dark.fg_label}
format-padding = 1

[module/kb]
type = internal/xkeyboard
blacklist-0 = scroll lock
content-padding = 1
format = <label-indicator>
format-background = ${colors_vscode_dark.bg_light}
format-padding = 0
format-spacing = 1
label-indicator-off-capslock = CAPS
label-indicator-off-capslock-foreground = ${colors_vscode_dark.fg_disabled}
label-indicator-off-numlock = NUM
label-indicator-off-numlock-foreground = ${colors_vscode_dark.fg_disabled}
label-indicator-on-capslock = CAPS
label-indicator-on-numlock = NUM

[module/ewmh]
type = internal/xworkspaces
enable-scroll = false
format-background = ${colors_vscode_dark.bg_light}
label-active = %name%
label-active-background = ${colors_vscode_dark.bg_active}
label-active-padding = 1
label-empty = %name%
label-empty-background = ${colors_vscode_dark.bg_light}
label-empty-foreground = ${colors_vscode_dark.fg_monitor_empty}
label-empty-padding = 1
label-occupied = %name%
label-occupied-background = ${colors_vscode_dark.bg_light}
label-occupied-padding = 1
label-urgent = %name%
label-urgent-background = ${colors_vscode_dark.bg_urgent}
label-urgent-padding = 1

[module/date]
type = internal/date
date = %a %d %b %Y
label = %date%  %time%
label-background = ${colors_vscode_dark.bg_dark}
label-foreground = ${colors_vscode_dark.fg_white}
label-padding = 2
time = %H:%M:%S

[module/upl]
type = custom/text
click-left = urxvt -name wrapper -e sh -c "echo 'Installing updates' && yay && read -p 'Finished. Press [Enter] to exit...'"
click-right = /usr/bin/polybar-msg action ups hook 0
;fa-rotate
format = " "
format-font = 3
format-background = ${colors_vscode_dark.bg_dark}
format-foreground = ${colors_vscode_dark.fg_label}
format-padding = 1

[module/ups]
type = custom/ipc
hook-0 = echo "$(checkupdates | wc -l) | $(yay -Qua | wc -l) "
hook-1 = echo "? | ? "
initial = 2
format-background = ${colors_vscode_dark.bg_dark}
format-foreground = ${colors_vscode_dark.fg_white}
